//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.inscripcion = new HashSet<inscripcion>();
            this.relAlumnoMedicamento = new HashSet<relAlumnoMedicamento>();
        }
    
        public int idAlumno { get; set; }
        public Nullable<int> idEscuela { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string tipoSangre { get; set; }
        public bool bAutorizacionMedicamento { get; set; }
        public bool bActivo { get; set; }
    
        public virtual escuela escuela { get; set; }
        public virtual ICollection<inscripcion> inscripcion { get; set; }
        public virtual ICollection<relAlumnoMedicamento> relAlumnoMedicamento { get; set; }
    }
}
