//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class avisoPrivacidad
    {
        public int idAvisoPrivacidad { get; set; }
        public int idEscuela { get; set; }
        public string instrucciones { get; set; }
        public string contenido { get; set; }
        public System.DateTime vigencia { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<bool> bActivo { get; set; }
        public Nullable<int> version { get; set; }
    }
}
