//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class escuela
    {
        public escuela()
        {
            this.alumno = new HashSet<alumno>();
            this.relEscuelaServicio = new HashSet<relEscuelaServicio>();
            this.publicacion = new HashSet<publicacion>();
            this.usuario = new HashSet<usuario>();
            this.relUsuarioRol = new HashSet<relUsuarioRol>();
        }
    
        public int idEscuela { get; set; }
        public string nombre { get; set; }
        public string RFC { get; set; }
        public string claveSEP { get; set; }
        public string direccion_calle { get; set; }
        public string direccion_numero { get; set; }
        public string direccion_estado { get; set; }
        public string direccion_pais { get; set; }
        public string direccion_cp { get; set; }
        public string contacto_responsable { get; set; }
        public string contacto_telefono { get; set; }
        public string contacto_extension { get; set; }
        public bool bActivo { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
        public virtual ICollection<relEscuelaServicio> relEscuelaServicio { get; set; }
        public virtual ICollection<publicacion> publicacion { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual ICollection<relUsuarioRol> relUsuarioRol { get; set; }
    }
}
