//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatusPublicacion
    {
        public estatusPublicacion()
        {
            this.publicacion = new HashSet<publicacion>();
        }
    
        public int idEstatus { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<publicacion> publicacion { get; set; }
    }
}
