//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.notificacion = new HashSet<notificacion>();
        }
    
        public int idEvento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string accion { get; set; }
        public string vista { get; set; }
    
        public virtual ICollection<notificacion> notificacion { get; set; }
    }
}
