//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public inscripcion()
        {
            this.relInscripcionEtapa = new HashSet<relInscripcionEtapa>();
        }
    
        public int idInscripcion { get; set; }
        public int idAlumno { get; set; }
        public int idPeriodo { get; set; }
        public bool bInscrito { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual cicloAcademico cicloAcademico { get; set; }
        public virtual ICollection<relInscripcionEtapa> relInscripcionEtapa { get; set; }
    }
}
