//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion
    {
        public int idNotificacion { get; set; }
        public int idEvento { get; set; }
        public int idUsuario { get; set; }
        public bool bActivo { get; set; }
        public Nullable<System.DateTime> fechaEvento { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
