//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        public int idPublicacion { get; set; }
        public int idEscuela { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public bool publico { get; set; }
        public int idEstatus { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<bool> bFecha { get; set; }
    
        public virtual escuela escuela { get; set; }
        public virtual estatusPublicacion estatusPublicacion { get; set; }
    }
}
