//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class relEscuelaServicio
    {
        public int id { get; set; }
        public int idEscuela { get; set; }
        public int idServicio { get; set; }
        public bool bActivo { get; set; }
        public string fechaModificacion { get; set; }
    
        public virtual escuela escuela { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
