//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class relEscuelaTema
    {
        public int id { get; set; }
        public int idEscuela { get; set; }
        public int idTema { get; set; }
        public bool bActivo { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    }
}
