//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class relInscripcionEtapa
    {
        public int id { get; set; }
        public int idInscripcion { get; set; }
        public int idEtapaInscripcion { get; set; }
        public bool bCompleto { get; set; }
    
        public virtual etapaInscripcion etapaInscripcion { get; set; }
        public virtual inscripcion inscripcion { get; set; }
    }
}
