//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaaSEntities : DbContext
    {
        public SaaSEntities()
            : base("name=SaaSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alumno> alumno { get; set; }
        public DbSet<avisoPrivacidad> avisoPrivacidad { get; set; }
        public DbSet<cicloAcademico> cicloAcademico { get; set; }
        public DbSet<contrato> contrato { get; set; }
        public DbSet<escuela> escuela { get; set; }
        public DbSet<estatusPublicacion> estatusPublicacion { get; set; }
        public DbSet<etapaInscripcion> etapaInscripcion { get; set; }
        public DbSet<evento> evento { get; set; }
        public DbSet<inscripcion> inscripcion { get; set; }
        public DbSet<medicamento> medicamento { get; set; }
        public DbSet<mensaje> mensaje { get; set; }
        public DbSet<notificacion> notificacion { get; set; }
        public DbSet<publicacion> publicacion { get; set; }
        public DbSet<relAlumnoMedicamento> relAlumnoMedicamento { get; set; }
        public DbSet<relEscuelaServicio> relEscuelaServicio { get; set; }
        public DbSet<relEscuelaTema> relEscuelaTema { get; set; }
        public DbSet<relInscripcionEtapa> relInscripcionEtapa { get; set; }
        public DbSet<relUsuarioRol> relUsuarioRol { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<servicio> servicio { get; set; }
        public DbSet<tema> tema { get; set; }
        public DbSet<tutoria> tutoria { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
