//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutoria
    {
        public int idTutoria { get; set; }
        public int idUsuario { get; set; }
        public int idAlumno { get; set; }
        public bool bAutorizado { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
