//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSaaS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.mensaje = new HashSet<mensaje>();
            this.mensaje1 = new HashSet<mensaje>();
            this.notificacion = new HashSet<notificacion>();
            this.relUsuarioRol = new HashSet<relUsuarioRol>();
        }
    
        public int idUsuario { get; set; }
        public Nullable<int> idEscuela { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string cuenta { get; set; }
        public string nomina { get; set; }
        public string contrasena { get; set; }
        public string sal { get; set; }
        public bool bActivo { get; set; }
        public string direccion_calle { get; set; }
        public string direccion_numero { get; set; }
        public string direccion_ciudad { get; set; }
        public string direccion_estado { get; set; }
        public string direccion_pais { get; set; }
        public string direccion_cp { get; set; }
        public string contacto_telefono { get; set; }
        public string contacto_extension { get; set; }
        public string contacto_movil { get; set; }
        public string tituloTrato { get; set; }
        public Nullable<System.DateTime> fechaUltimoAcceso { get; set; }
        public string correoElectronico { get; set; }
        public Nullable<bool> bReinicioContrasena { get; set; }
    
        public virtual escuela escuela { get; set; }
        public virtual ICollection<mensaje> mensaje { get; set; }
        public virtual ICollection<mensaje> mensaje1 { get; set; }
        public virtual ICollection<notificacion> notificacion { get; set; }
        public virtual ICollection<relUsuarioRol> relUsuarioRol { get; set; }
    }
}
